variable "name" {
  description = "Managed PostgreSQL cluster name."
  type        = string
}

variable "folder_id" {
  description = "Yandex Cloud folder ID."
  type        = string
}

variable "network_id" {
  description = "VPC network ID. This is immutable for a Managed PostgreSQL cluster."
  type        = string
}

variable "security_group_id" {
  description = "Security group allowing private PostgreSQL access."
  type        = string
}

variable "subnet_id" {
  description = "Subnet for the first database host."
  type        = string
}

variable "zone" {
  description = "Availability zone for the first database host."
  type        = string
  default     = "ru-central1-a"
}

variable "environment" {
  description = "Managed PostgreSQL environment: PRESTABLE for dev, PRODUCTION for prod."
  type        = string
  default     = "PRESTABLE"

  validation {
    condition     = contains(["PRESTABLE", "PRODUCTION"], var.environment)
    error_message = "environment must be PRESTABLE or PRODUCTION."
  }
}

variable "postgres_version" {
  description = "PostgreSQL major version supported by Yandex Managed PostgreSQL."
  type        = string
  default     = "18"
}

variable "resource_preset_id" {
  description = "Yandex Managed PostgreSQL host class."
  type        = string
  default     = "s2.micro"
}

variable "disk_type_id" {
  description = "Managed PostgreSQL disk type."
  type        = string
  default     = "network-ssd"
}

variable "disk_size_gb" {
  description = "Initial disk size in GiB."
  type        = number
  default     = 20
}

variable "database_name" {
  description = "Application database name."
  type        = string
  default     = "tehkarta"
}

variable "database_user" {
  description = "Application database owner. Password is generated by Yandex Connection Manager and stored in Lockbox."
  type        = string
  default     = "tehkarta_app"
}

variable "deletion_protection" {
  description = "Enable Yandex resource deletion protection. Production must set true."
  type        = bool
  default     = false
}

variable "labels" {
  description = "Common resource labels."
  type        = map(string)
  default     = {}
}
