import { useState } from 'react';
import type { Course } from '../../../entities/course/model.js';
import { useKnowledgeSpaces } from '../model/useKnowledgeSpaces.js';
import type { KnowledgeDocumentType } from '../model/types.js';
import './knowledge-space.css';

const documentTypes:Array<{id:KnowledgeDocumentType;label:string}>=[{id:'WORKING_PROGRAM',label:'Рабочая программа'},{id:'TEXTBOOK',label:'Учебник'},{id:'METHOD_GUIDE',label:'Методическое пособие'},{id:'ATLAS',label:'Атлас'},{id:'WORKBOOK',label:'Рабочая тетрадь'},{id:'ASSESSMENT',label:'Оценочные материалы'},{id:'LOCAL_MATERIAL',label:'Локальный материал'}];

export function KnowledgeSpacePanel({course,onCourseLinked}:{course:Course|null;onCourseLinked:()=>Promise<void>}) {
  const model=useKnowledgeSpaces(course,onCourseLinked); const [subjectId,setSubjectId]=useState(course?.subject??''); const [grade,setGrade]=useState(course?.grade??9); const [umkId,setUmkId]=useState(course?.contentPackId??''); const [file,setFile]=useState<File|null>(null); const [documentType,setDocumentType]=useState<KnowledgeDocumentType>('WORKING_PROGRAM'); const [sourceRevision,setSourceRevision]=useState('1'); const selected=model.spaces.find((item)=>item.id===model.selectedId);
  return <div className="knowledge-admin"><header><span className="eyebrow">Администрирование знаний</span><h1>Knowledge Spaces</h1><p>Документы учреждения изолированы по предмету, классу и УМК. AI видит только опубликованные chunks выбранного пространства.</p></header>
    <div className="knowledge-grid"><section className="knowledge-card"><h2>1. Пространство</h2><div className="knowledge-form"><label>Предмет<input value={subjectId} onChange={(event)=>setSubjectId(event.target.value)}/></label><label>Класс<input type="number" min="1" max="11" value={grade} onChange={(event)=>setGrade(Number(event.target.value))}/></label><label>УМК<input value={umkId} onChange={(event)=>setUmkId(event.target.value)}/></label><button className="button button-primary" type="button" disabled={model.busy!==null||!subjectId.trim()||!umkId.trim()} onClick={()=>void model.create({subjectId,grade,umkId}).catch(()=>undefined)}>Создать</button></div><div className="knowledge-space-list">{model.spaces.map((space)=><button type="button" className={space.id===model.selectedId?'is-selected':''} key={space.id} onClick={()=>model.setSelectedId(space.id)}><strong>{space.subjectId} · {space.grade} класс</strong><span>{space.umkId} · {space.status==='PUBLISHED'?'Опубликовано':'Черновик'}</span></button>)}</div></section>
      <section className="knowledge-card"><h2>2. Загрузка и проверка</h2>{selected?<><div className="knowledge-form"><label>Тип документа<select value={documentType} onChange={(event)=>setDocumentType(event.target.value as KnowledgeDocumentType)}>{documentTypes.map((type)=><option key={type.id} value={type.id}>{type.label}</option>)}</select></label><label>Версия источника<input value={sourceRevision} onChange={(event)=>setSourceRevision(event.target.value)}/></label><label className="knowledge-file">PDF, TXT или Markdown<input type="file" accept=".pdf,.txt,.md,text/plain,text/markdown,application/pdf" onChange={(event)=>setFile(event.target.files?.[0]??null)}/></label><button className="button button-primary" type="button" disabled={!file||model.busy!==null} onClick={()=>file&&void model.upload({file,documentType,title:file.name,sourceRevision}).then(()=>setFile(null)).catch(()=>undefined)}>Разобрать и индексировать</button></div><div className="knowledge-document-list">{model.documents.map((document)=><article key={document.id}><div><strong>{document.title}</strong><span>{documentTypes.find((item)=>item.id===document.documentType)?.label} · {document.chunkCount} фрагментов · версия {document.sourceRevision}</span></div>{document.status==='PUBLISHED'?<span className="source-approved">✓ Опубликован</span>:<button className="button button-secondary" type="button" disabled={model.busy!==null} onClick={()=>void model.publish(document.id).catch(()=>undefined)}>Проверено — опубликовать</button>}</article>)}</div></>:<p>Создайте или выберите пространство.</p>}</section>
    </div>{course&&selected?<footer className="knowledge-link"><div><strong>Привязка к курсу «{course.title}»</strong><p>Предмет и класс должны совпадать; привязать можно только опубликованное пространство.</p></div><button className="button button-primary" type="button" disabled={selected.status!=='PUBLISHED'||model.busy!==null||course.knowledgeSpaceId===selected.id} onClick={()=>void model.linkCourse().catch(()=>undefined)}>{course.knowledgeSpaceId===selected.id?'✓ Уже привязано':'Использовать для курса'}</button></footer>:null}</div>;
}
